# Generated by Django 3.1.3 on 2021-07-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_studentresult_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='myid',
            field=models.IntegerField(default=1),
        ),
    ]
