# Generated by Django 3.1.3 on 2021-07-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentresult_myid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='student_id',
        ),
    ]
